/*
 * Generated by gdbus-codegen 2.30.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "gio_gpsd.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gpsd
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:gpsdOrgGpsd
 * @title: gpsdOrgGpsd
 * @short_description: Generated C code for the org.gpsd D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gpsd.top_of_page">org.gpsd</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gpsd ---- */

static const _ExtendedGDBusArgInfo _gpsd_org_gpsd_signal_info_fix_ARG_data =
{
  {
    -1,
    "data",
    "ad{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gpsd_org_gpsd_signal_info_fix_ARG_pointers[] =
{
  &_gpsd_org_gpsd_signal_info_fix_ARG_data,
  NULL
};

static const _ExtendedGDBusSignalInfo _gpsd_org_gpsd_signal_info_fix =
{
  {
    -1,
    "fix",
    (GDBusArgInfo **) &_gpsd_org_gpsd_signal_info_fix_ARG_pointers,
    NULL
  },
  "fix"
};

static const _ExtendedGDBusArgInfo _gpsd_org_gpsd_signal_info_telemetry_ARG_data =
{
  {
    -1,
    "data",
    "ad{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _gpsd_org_gpsd_signal_info_telemetry_ARG_pointers[] =
{
  &_gpsd_org_gpsd_signal_info_telemetry_ARG_data,
  NULL
};

static const _ExtendedGDBusSignalInfo _gpsd_org_gpsd_signal_info_telemetry =
{
  {
    -1,
    "telemetry",
    (GDBusArgInfo **) &_gpsd_org_gpsd_signal_info_telemetry_ARG_pointers,
    NULL
  },
  "telemetry"
};

static const _ExtendedGDBusSignalInfo * const _gpsd_org_gpsd_signal_info_pointers[] =
{
  &_gpsd_org_gpsd_signal_info_fix,
  &_gpsd_org_gpsd_signal_info_telemetry,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gpsd_org_gpsd_interface_info =
{
  {
    -1,
    "org.gpsd",
    NULL,
    (GDBusSignalInfo **) &_gpsd_org_gpsd_signal_info_pointers,
    NULL,
    NULL
  },
  "org-gpsd",
};


/**
 * gpsd_org_gpsd_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gpsd.top_of_page">org.gpsd</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gpsd_org_gpsd_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gpsd_org_gpsd_interface_info;
}

/**
 * gpsd_org_gpsd_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #gpsdOrgGpsd interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gpsd_org_gpsd_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * gpsdOrgGpsd:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gpsd.top_of_page">org.gpsd</link>.
 */

/**
 * gpsdOrgGpsdIface:
 * @parent_iface: The parent interface.
 * @fix: Handler for the #gpsdOrgGpsd::fix signal.
 * @telemetry: Handler for the #gpsdOrgGpsd::telemetry signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gpsd.top_of_page">org.gpsd</link>.
 */

static void
gpsd_org_gpsd_default_init (gpsdOrgGpsdIface *iface)
{
  /* GObject signals for received D-Bus signals: */
  /**
   * gpsdOrgGpsd::fix:
   * @object: A #gpsdOrgGpsd.
   * @arg_data: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-gpsd.fix">"fix"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("fix",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (gpsdOrgGpsdIface, fix),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  /**
   * gpsdOrgGpsd::telemetry:
   * @object: A #gpsdOrgGpsd.
   * @arg_data: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-gpsd.telemetry">"telemetry"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("telemetry",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (gpsdOrgGpsdIface, telemetry),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

}

typedef gpsdOrgGpsdIface gpsdOrgGpsdInterface;
G_DEFINE_INTERFACE (gpsdOrgGpsd, gpsd_org_gpsd, G_TYPE_OBJECT);

/**
 * gpsd_org_gpsd_emit_fix:
 * @object: A #gpsdOrgGpsd.
 * @arg_data: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-gpsd.fix">"fix"</link> D-Bus signal.
 */
void
gpsd_org_gpsd_emit_fix (
    gpsdOrgGpsd *object,
    GVariant *arg_data)
{
  g_signal_emit_by_name (object, "fix", arg_data);
}

/**
 * gpsd_org_gpsd_emit_telemetry:
 * @object: A #gpsdOrgGpsd.
 * @arg_data: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-gpsd.telemetry">"telemetry"</link> D-Bus signal.
 */
void
gpsd_org_gpsd_emit_telemetry (
    gpsdOrgGpsd *object,
    GVariant *arg_data)
{
  g_signal_emit_by_name (object, "telemetry", arg_data);
}

/* ------------------------------------------------------------------------ */

/**
 * gpsdOrgGpsdProxy:
 *
 * The #gpsdOrgGpsdProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * gpsdOrgGpsdProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #gpsdOrgGpsdProxy.
 */

struct _gpsdOrgGpsdProxyPrivate
{
  GData *qdata;
};

static void gpsd_org_gpsd_proxy_iface_init (gpsdOrgGpsdIface *iface);

G_DEFINE_TYPE_WITH_CODE (gpsdOrgGpsdProxy, gpsd_org_gpsd_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GPSD_TYPE_ORG_GPSD, gpsd_org_gpsd_proxy_iface_init));

static void
gpsd_org_gpsd_proxy_finalize (GObject *object)
{
  gpsdOrgGpsdProxy *proxy = GPSD_ORG_GPSD_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gpsd_org_gpsd_proxy_parent_class)->finalize (object);
}

static void
gpsd_org_gpsd_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
gpsd_org_gpsd_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
gpsd_org_gpsd_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gpsd_org_gpsd_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GPSD_TYPE_ORG_GPSD);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GPSD_TYPE_ORG_GPSD);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gpsd_org_gpsd_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  gpsdOrgGpsdProxy *proxy = GPSD_ORG_GPSD_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gpsd_org_gpsd_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gpsd_org_gpsd_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
gpsd_org_gpsd_proxy_init (gpsdOrgGpsdProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GPSD_TYPE_ORG_GPSD_PROXY, gpsdOrgGpsdProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gpsd_org_gpsd_interface_info ());
}

static void
gpsd_org_gpsd_proxy_class_init (gpsdOrgGpsdProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (gpsdOrgGpsdProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gpsd_org_gpsd_proxy_finalize;
  gobject_class->get_property = gpsd_org_gpsd_proxy_get_property;
  gobject_class->set_property = gpsd_org_gpsd_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gpsd_org_gpsd_proxy_g_signal;
  proxy_class->g_properties_changed = gpsd_org_gpsd_proxy_g_properties_changed;

}

static void
gpsd_org_gpsd_proxy_iface_init (gpsdOrgGpsdIface *iface)
{
}

/**
 * gpsd_org_gpsd_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gpsd.top_of_page">org.gpsd</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gpsd_org_gpsd_proxy_new_finish() to get the result of the operation.
 *
 * See gpsd_org_gpsd_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gpsd_org_gpsd_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GPSD_TYPE_ORG_GPSD_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gpsd", NULL);
}

/**
 * gpsd_org_gpsd_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gpsd_org_gpsd_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gpsd_org_gpsd_proxy_new().
 *
 * Returns: (transfer full) (type gpsdOrgGpsdProxy): The constructed proxy object or %NULL if @error is set.
 */
gpsdOrgGpsd *
gpsd_org_gpsd_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GPSD_ORG_GPSD (ret);
  else
    return NULL;
}

/**
 * gpsd_org_gpsd_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gpsd.top_of_page">org.gpsd</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gpsd_org_gpsd_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type gpsdOrgGpsdProxy): The constructed proxy object or %NULL if @error is set.
 */
gpsdOrgGpsd *
gpsd_org_gpsd_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GPSD_TYPE_ORG_GPSD_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gpsd", NULL);
  if (ret != NULL)
    return GPSD_ORG_GPSD (ret);
  else
    return NULL;
}


/**
 * gpsd_org_gpsd_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gpsd_org_gpsd_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call gpsd_org_gpsd_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gpsd_org_gpsd_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gpsd_org_gpsd_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GPSD_TYPE_ORG_GPSD_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gpsd", NULL);
}

/**
 * gpsd_org_gpsd_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gpsd_org_gpsd_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gpsd_org_gpsd_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type gpsdOrgGpsdProxy): The constructed proxy object or %NULL if @error is set.
 */
gpsdOrgGpsd *
gpsd_org_gpsd_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GPSD_ORG_GPSD (ret);
  else
    return NULL;
}

/**
 * gpsd_org_gpsd_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gpsd_org_gpsd_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gpsd_org_gpsd_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type gpsdOrgGpsdProxy): The constructed proxy object or %NULL if @error is set.
 */
gpsdOrgGpsd *
gpsd_org_gpsd_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GPSD_TYPE_ORG_GPSD_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gpsd", NULL);
  if (ret != NULL)
    return GPSD_ORG_GPSD (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * gpsdOrgGpsdSkeleton:
 *
 * The #gpsdOrgGpsdSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * gpsdOrgGpsdSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #gpsdOrgGpsdSkeleton.
 */

struct _gpsdOrgGpsdSkeletonPrivate
{
  GValueArray *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex *lock;
};

static void
_gpsd_org_gpsd_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  gpsdOrgGpsdSkeleton *skeleton = GPSD_ORG_GPSD_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = {0};
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GPSD_TYPE_ORG_GPSD);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GPSD_TYPE_ORG_GPSD);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gpsd_org_gpsd_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  gpsdOrgGpsdSkeleton *skeleton = GPSD_ORG_GPSD_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gpsd_org_gpsd_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gpsd_org_gpsd_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  gpsdOrgGpsdSkeleton *skeleton = GPSD_ORG_GPSD_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gpsd_org_gpsd_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gpsd_org_gpsd_skeleton_vtable =
{
  _gpsd_org_gpsd_skeleton_handle_method_call,
  _gpsd_org_gpsd_skeleton_handle_get_property,
  _gpsd_org_gpsd_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
gpsd_org_gpsd_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return gpsd_org_gpsd_interface_info ();
}

static GDBusInterfaceVTable *
gpsd_org_gpsd_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_gpsd_org_gpsd_skeleton_vtable;
}

static GVariant *
gpsd_org_gpsd_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  gpsdOrgGpsdSkeleton *skeleton = GPSD_ORG_GPSD_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gpsd_org_gpsd_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gpsd_org_gpsd_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gpsd_org_gpsd_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gpsd_org_gpsd_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gpsd", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
gpsd_org_gpsd_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_gpsd_org_gpsd_on_signal_fix (
    gpsdOrgGpsd *object,
    GVariant *arg_data)
{
  gpsdOrgGpsdSkeleton *skeleton = GPSD_ORG_GPSD_SKELETON (object);
  GDBusConnection *connection = g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton));
  if (connection == NULL)
    return;
  g_dbus_connection_emit_signal (connection,
    NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gpsd", "fix",
    g_variant_new ("(@ad{sv})",
                   arg_data), NULL);
}

static void
_gpsd_org_gpsd_on_signal_telemetry (
    gpsdOrgGpsd *object,
    GVariant *arg_data)
{
  gpsdOrgGpsdSkeleton *skeleton = GPSD_ORG_GPSD_SKELETON (object);
  GDBusConnection *connection = g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton));
  if (connection == NULL)
    return;
  g_dbus_connection_emit_signal (connection,
    NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gpsd", "telemetry",
    g_variant_new ("(@ad{sv})",
                   arg_data), NULL);
}

static void gpsd_org_gpsd_skeleton_iface_init (gpsdOrgGpsdIface *iface);
G_DEFINE_TYPE_WITH_CODE (gpsdOrgGpsdSkeleton, gpsd_org_gpsd_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GPSD_TYPE_ORG_GPSD, gpsd_org_gpsd_skeleton_iface_init));

static void
gpsd_org_gpsd_skeleton_finalize (GObject *object)
{
  gpsdOrgGpsdSkeleton *skeleton = GPSD_ORG_GPSD_SKELETON (object);
  g_list_foreach (skeleton->priv->changed_properties, (GFunc) _changed_property_free, NULL);
  g_list_free (skeleton->priv->changed_properties);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  if (skeleton->priv->context != NULL)
    g_main_context_unref (skeleton->priv->context);
  g_mutex_free (skeleton->priv->lock);
  G_OBJECT_CLASS (gpsd_org_gpsd_skeleton_parent_class)->finalize (object);
}

static void
gpsd_org_gpsd_skeleton_init (gpsdOrgGpsdSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GPSD_TYPE_ORG_GPSD_SKELETON, gpsdOrgGpsdSkeletonPrivate);
  skeleton->priv->lock = g_mutex_new ();
  skeleton->priv->context = g_main_context_get_thread_default ();
  if (skeleton->priv->context != NULL)
    g_main_context_ref (skeleton->priv->context);
}

static void
gpsd_org_gpsd_skeleton_class_init (gpsdOrgGpsdSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (gpsdOrgGpsdSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gpsd_org_gpsd_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gpsd_org_gpsd_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gpsd_org_gpsd_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gpsd_org_gpsd_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gpsd_org_gpsd_skeleton_dbus_interface_get_vtable;
}

static void
gpsd_org_gpsd_skeleton_iface_init (gpsdOrgGpsdIface *iface)
{
  iface->fix = _gpsd_org_gpsd_on_signal_fix;
  iface->telemetry = _gpsd_org_gpsd_on_signal_telemetry;
}

/**
 * gpsd_org_gpsd_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gpsd.top_of_page">org.gpsd</link>.
 *
 * Returns: (transfer full) (type gpsdOrgGpsdSkeleton): The skeleton object.
 */
gpsdOrgGpsd *
gpsd_org_gpsd_skeleton_new (void)
{
  return GPSD_ORG_GPSD (g_object_new (GPSD_TYPE_ORG_GPSD_SKELETON, NULL));
}

